**Step 1: Importing NumPy**

Before working with matrices, you need to import NumPy.

In [1]:
import numpy as np

**Step 2: Creating Matrices**

NumPy uses the array function to create matrices.

In [2]:
# Creating a 2x2 matrix
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

print("Matrix A:")
print(matrix_a)

print("\nMatrix B:")
print(matrix_b)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]


**Step 3: Basic Matrix Operations**

***a) Addition:***

In [3]:
result_add = matrix_a + matrix_b

print("\nMatrix Addition:")
print(result_add)


Matrix Addition:
[[ 6  8]
 [10 12]]


***b) Subtraction:***

In [4]:
result_sub = matrix_a - matrix_b

print("\nMatrix Subtraction:")
print(result_sub)


Matrix Subtraction:
[[-4 -4]
 [-4 -4]]


**Step 4: Matrix Multiplication**

NumPy provides two methods for matrix multiplication:
- Element-wise Multiplication: Use the * operator.
- Matrix Product: Use @ or np.dot.

In [6]:
# Element-wise multiplication
element_wise = matrix_a * matrix_b

print("\nElement-wise Multiplication:")
print(element_wise)


Element-wise Multiplication:
[[ 5 12]
 [21 32]]


In [7]:
# Matrix product
matrix_product = np.dot(matrix_a, matrix_b)

print("\nMatrix Product:")
print(matrix_product)


Matrix Product:
[[19 22]
 [43 50]]


In [8]:
# Alternative using @
matrix_product_alt = matrix_a @ matrix_b

print("\nMatrix Product (using @):")
print(matrix_product_alt)


Matrix Product (using @):
[[19 22]
 [43 50]]


**Step 5: Transpose of a Matrix**
    
Transpose switches rows and columns.

In [9]:
transpose_a = matrix_a.T

print("\nTranspose of Matrix A:")
print(transpose_a)


Transpose of Matrix A:
[[1 3]
 [2 4]]


**Step 6: Determinant of a Matrix**
    
Use np.linalg.det() to find the determinant of a matrix.

In [10]:
det_a = np.linalg.det(matrix_a)

print("\nDeterminant of Matrix A:")
print(det_a)


Determinant of Matrix A:
-2.0000000000000004


**Step 7: Inverse of a Matrix**
    
Use np.linalg.inv() to find the inverse of a matrix.

In [12]:
inverse_a = np.linalg.inv(matrix_a)

print("\nInverse of Matrix A:")
print(inverse_a)


Inverse of Matrix A:
[[-2.   1. ]
 [ 1.5 -0.5]]


**Step 8: Eigenvalues and Eigenvectors**

Use np.linalg.eig() to find eigenvalues and eigenvectors.

In [13]:
eigenvalues, eigenvectors = np.linalg.eig(matrix_a)

print("\nEigenvalues of Matrix A:")
print(eigenvalues)

print("\nEigenvectors of Matrix A:")
print(eigenvectors)


Eigenvalues of Matrix A:
[-0.37228132  5.37228132]

Eigenvectors of Matrix A:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


**Step 9: Solving Linear Equations**
    
Solve equations of the form Ax = B using np.linalg.solve().

In [14]:
B = np.array([1, 2])
x = np.linalg.solve(matrix_a, B)

print("\nSolution to Ax = B:")
print(x)


Solution to Ax = B:
[0.  0.5]
